---
title: "ZULE's Project Starter Kit"
author: "Isabella Richmond & Kayleigh Hutt-Taylor"
date: October 24, 2022
format: 
  revealjs:
    theme: dark
editor: visual
---

# Part I: Prep Work
## Learning Goals

My goal for this workshop is to give everyone the tools to:

- Confidently start a project in R 
- Manage files in a way that is reproducible and easy to understand
- Allow people to document progress on their projects
- Know what they want to learn more about/ask me about in the coming months

## Software Installation

- **CHECK-IN: does everyone have everything working/installed?**
- Absolutely the hardest part of this workshop 
- Thank you for doing homework!!

. . .


- If you have technical issues throughout this presentation - raise your hand and we will either work through together or Kayleigh will help you troubleshoot


# Part II: GitHub
## GitHub & Version Control


## The Basics of GitHub


# Part III: R & RStudio

## RStudio Projects & Data Management


## File Management for R 


## Data in R!!!

# Clean Data
## Clean Data, Clean Mind

# Part 4: Resources
## Check 'em out! 
**this workshop - including examples & slides can all be found at: https://github.com/zule-lab/project-starter-workshop**
